//CURD
export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM_IN_CLIENT = 'UPDATE_ITEM_IN_CLIENT'
export const TOGGLE_ITEM = 'TOGGLE_ITEM'
export const UPDATE_ITEM_TITLE = 'UPDATE_ITEM_TITLE'
export const FETCH_ITEMS = 'FETCH_ITEMS'
export const FETCH_ITEMS_NOT_BOUGHT_YET = 'FETCH_ITEMS_NOT_BOUGHT_YET'
export const FETCH_ITEMS_BOUGHT = 'FETCH_ITEMS_BOUGHT'
export const DELETE_ITEM = 'DELETE_ITEM'